package com.fastcampus.kafkahandson.ugc.inspectedPost;

import com.fastcampus.kafkahandson.ugc.post.model.Post;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@RequiredArgsConstructor
@Getter
public class InspectedPost {
    private final Post post; // 컨텐츠
    private final String categoryName; // 컨텐츠명
    private final List<String> autoGeneratedTags; // ChatGpt로 받은 태그들
    private final LocalDateTime inspectedAt; // 검수한 날짜

    public static InspectedPost generate(
            Post post,
            String categoryName,
            List<String> autoGeneratedTags
    ) {
        return new InspectedPost(
                post,
                categoryName,
                autoGeneratedTags,
                LocalDateTime.now()
        );
    }
}
