server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://58.181.51.186:3306/campus?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: 58.181.51.186:9092,58.181.51.186:9093,58.181.51.186:9094
  data:
    redis:
      host: 58.181.51.186
      port: 6379